(function(){
var tl=function(n){var s='<div class="tl">';for(var i=0;i<7;i++)s+='<i class="'+(i<n?'d':i===n?'c':'')+'"></i>';return s+'</div>'};
var S=[
{t:'Tilbudet',w:'Tilbud',clk:'09:12',n:['E-post','Tilbudet ditt fra Kjøkkenstudio Hamar er klart'],h:'Tilbudet kommer i Min side',p:'Hanne får tilbudet med tegninger, design og pris. Hun kan se opsjonene, sammenligne og stille spørsmål der.',bak:['Tilbudet er laget fra CET uten taste-arbeid','Pris og leveringstid kommer fra leverandørene'],
 v:'<div class="hero">Ditt nye kjøkken</div><div class="c"><b>Tilbud 10087</b><div class="row"><span>Kjøkken og hvitevarer</span><span>312 400 kr</span></div><p>Gyldig til 1. november</p></div><div class="c"><b>Opsjon</b><div class="row"><span>Benkeplate i kompositt</span><span>+ 6 200 kr</span></div></div><button class="btn primary big" type="button">Se tilbudet</button>'},
{t:'Signering',w:'Kontrakt',clk:'19:40',n:['Min side','Kontrakten er klar til signering'],h:'Signerer med BankID via Penneo',p:'Hanne leser kontrakten og signerer på mobilen. Hun får bekreftelse med en gang.',bak:['Kontrakten kontrolleres mot ordren','Montasjen settes til uke 46','Leveringsukene regnes bakover'],
 v:tl(1)+'<div class="c"><b>Kjøpsavtale</b><p>Forbrukervilkår er lagt ved.</p></div><div class="c"><div class="row"><span>Sum</span><span>318 600 kr</span></div><div class="row"><span>Forskudd</span><span>30 %</span></div><div class="row"><span>Montasje</span><span>uke 46</span></div></div><button class="btn primary big" type="button">Signer med BankID</button>'},
{t:'Bekreftet',w:'Status',clk:'10:05',n:['SMS','Alt er bekreftet av leverandørene. Montasje uke 46.'],h:'Alt er bekreftet',p:'Når leverandørene har bekreftet, ser Hanne leveringsuke og montasje i Min side. Et avvik hos én leverandør løser selgeren uten at hun merker det.',bak:['Fem bestillinger gikk ut samtidig','Fire bekreftelser stemte','Ett avvik ble rettet av selgeren'],
 v:tl(2)+'<div class="c"><b>Bestilt og bekreftet</b><p>Levering uke 45, montasje uke 46</p></div><div class="c"><div class="row"><span>Kjøkken</span><span class="pill ok">Bekreftet</span></div><div class="row"><span>Hvitevarer</span><span class="pill ok">Bekreftet</span></div><div class="row"><span>Benkeplate</span><span class="pill ok">Bekreftet</span></div></div><div class="c"><b>Siste dag for endringer</b><p>Fredag uke 42</p></div>'},
{t:'Endring',w:'Endring',clk:'21:15',n:['Min side','Endringen din er bekreftet'],h:'Bytter en front',p:'Hanne vil ha tett front i stedet for glass. Hun sender ønsket fra Min side før siste endringsdag og ser ny pris før hun godkjenner.',bak:['Endringsordren går med samme referanse','Endrings-OB kontrolleres automatisk'],
 v:tl(3)+'<div class="c"><b>Endringsønske</b><p>Høyskap: glassfront → tett front</p><div class="row"><span>Ny pris</span><span>− 1 200 kr</span></div></div><div class="c"><div class="row"><span>Status</span><span class="pill ok">Bekreftet</span></div></div>'},
{t:'Levering',w:'Levering',clk:'15:30',n:['SMS','Levering tirsdag 08–12. Følg sendingen her.'],h:'Vet når varene kommer',p:'To dager før levering kommer SMS med dag, tidsvindu og sporing. Hanne kan legge til beskjed om innkjøring eller nøkkel.',bak:['Leveringsvarsel fra transportøren','SMS sendes via Unifon','Digitalt leveringsbevis til ordren'],
 v:tl(4)+'<div class="c"><b>Levering tirsdag</b><p>Kl. 08–12 · 9 kolli</p><div class="row"><span>Status</span><span class="pill info">Underveis</span></div></div><div class="c"><b>Beskjed til sjåføren</b><p>«Bruk inngangen bak huset.»</p></div>'},
{t:'Montasje',w:'Montasje',clk:'15:20',n:['SMS','Montøren er ferdig. Godkjenn jobben i Min side.'],h:'Ferdig montert',p:'Montøren sier fra når han kommer, og Hanne signerer på iPaden når kjøkkenet er ferdig. Et skadet sidepanel er allerede meldt til leverandøren.',bak:['KS Kjøkken med bilder i Hengsel','Avvik sendt rett til Sigdal med bilde','Erstatning uke 47'],
 v:tl(5)+'<div class="c"><b>Montasje ferdig</b><p>Demo Montasje · 2 dager</p></div><div class="c"><b>Én ting gjenstår</b><p>Nytt sidepanel kommer uke 47. Du trenger ikke gjøre noe.</p></div><button class="btn primary big" type="button">Godkjenn jobben</button>'},
{t:'FDV',w:'Ditt kjøkken',clk:'09:00',n:['E-post','Ditt nye kjøkken: alt om stell og garanti'],h:'Alt om kjøkkenet på ett sted',p:'Hanne får FDV-pakken med produkter, stell, garanti og sluttfaktura. Den ligger i Min side for alltid.',bak:['FDV laget fra produktdataene','Sluttfaktura fra PowerOffice'],
 v:tl(6)+'<div class="c"><b>Ditt nye kjøkken</b><p>FDV, stell og vedlikehold</p></div><div class="c"><div class="row"><span>Garanti</span><span>5 år</span></div><div class="row"><span>Sluttfaktura</span><span class="pill ok">Betalt</span></div></div><button class="btn primary big" type="button">Last ned FDV</button>'},
{t:'Reklamasjon',w:'Hjelp',clk:'11:42',n:['Min side','Vi har mottatt saken din'],h:'Hvis noe skjer',p:'En skuff har slått seg. Hanne melder det med bilde i Min side og ser status hele veien, uten å lete etter telefonnummer.',bak:['Saken kobles til riktig ordre og artikkel','Leverandøren får den med bilde'],
 v:tl(7)+'<div class="c"><b>Ny sak</b><p>Skuff U4 lukker ikke helt</p><div class="pics" style="height:70px;border-radius:10px;background:var(--line)"></div></div><div class="c"><div class="row"><span>Status</span><span class="pill info">Montør kommer torsdag</span></div></div>'}
];
var cur=0,T=null,$=function(i){return document.getElementById(i)},stp=$('steps');
S.forEach(function(s,i){var b=document.createElement('button');b.type='button';b.innerHTML='<i></i><span>'+(i+1)+' · '+s.t+'</span>';b.onclick=function(){stop();go(i)};stp.appendChild(b)});
function go(i){cur=i;var s=S[i];$('v').innerHTML=s.v;$('where').textContent=s.w;$('clock').textContent=s.clk;$('k').textContent='Steg '+(i+1)+' av '+S.length;$('h').textContent=s.h;$('p').textContent=s.p;$('bk').innerHTML=s.bak.map(function(x){return '<li>'+x+'</li>'}).join('');
 var n=$('nt');n.classList.remove('show');$('ntk').textContent=s.n[0];$('ntt').textContent=s.n[1];setTimeout(function(){n.classList.add('show')},250);setTimeout(function(){n.classList.remove('show')},3400);
 [].forEach.call(stp.children,function(b,j){b.classList.toggle('on',j===i);b.classList.toggle('p',j<i)});var cb=stp.children[i];stp.scrollLeft=cb.offsetLeft-(stp.clientWidth-cb.offsetWidth)/2;$('pv').disabled=i===0;$('nx').disabled=i===S.length-1}
function stop(){clearInterval(T);T=null;$('pl').textContent='Spill av'}
$('pv').onclick=function(){stop();go(cur-1)};$('nx').onclick=function(){stop();go(cur+1)};
$('pl').onclick=function(){if(T){stop();return}$('pl').textContent='Pause';if(cur===S.length-1)go(0);T=setInterval(function(){if(cur>=S.length-1){stop();return}go(cur+1)},5200)};
document.addEventListener('keydown',function(e){if(e.key==='ArrowRight'&&cur<S.length-1){stop();go(cur+1)}if(e.key==='ArrowLeft'&&cur>0){stop();go(cur-1)}});
go(0);
})();
